version: '3'

services:
  api:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  test:
    build: .
    command: python -m unittest discover
    volumes:
      - .:/app