name: Docker App Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Build da imagem Docker
      run: docker build -t minha-api ./lab_api

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Build da imagem (de novo para testar)
      run: docker build -t minha-api ./lab_api

    - name: Rodar container em background
      run: docker run -d -p 1313:1313 --name minha-api-container minha-api

    - name: Esperar API subir
      run: sleep 5

    - name: Testar endpoint (exemplo com curl)
      run: |
        curl --fail http://localhost:1313 || exit 1

    - name: Parar o container
      run: docker stop minha-api-container
