name: Docker App Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Build da imagem Docker
      run: docker build -t minha-api .

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Rodar container em background
      run: docker compose run api python -m unittest discover Devops/lab_api/

    Deploy:
      runs-on: ubuntu-latest
      needs: test 
      
      steps:
      - name: DEPLOY
        run: curl -x POST https://api.render.com/deploy/srv-d1347v49c44c738t3bq0?key=bdT0RZoeqL4